import{initializeApp}from"https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js";import{getAuth,onAuthStateChanged,signOut}from"https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js";
const config={apiKey:"AIzaSyCfHLrtPMnLtfU-PvsVf5QCOXKmuZya51I",authDomain:"loner-hq.firebaseapp.com",projectId:"loner-hq",storageBucket:"loner-hq.firebasestorage.app",messagingSenderId:"290842361996",appId:"1:290842361996:web:f1010f32a520a7148f7ba9",measurementId:"G-0X2Y1KQFEE"},auth=getAuth(initializeApp(config)),id="origem-especies",total=502;
let user,reading={};
const input=document.querySelector("#current-page"),fill=document.querySelector("#progress-fill"),label=document.querySelector("#progress-label"),message=document.querySelector("#progress-message"),mainButton=document.querySelector("#save-book");
function avatar(n){const i=(n||"L")[0].toUpperCase(),s=`<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100"><rect width="100%" height="100%" fill="#3b2518"/><text x="50%" y="56%" text-anchor="middle" fill="#e6d2a8" font-size="45">${i}</text></svg>`;return`data:image/svg+xml,${encodeURIComponent(s)}`}
function key(){return`loner-reading-${user.uid}`}function load(){try{reading=JSON.parse(localStorage.getItem(key())||"{}")}catch{reading={}};reading[id]??={status:"quero-ler",page:0};paint()}
function save(show=true){localStorage.setItem(key(),JSON.stringify(reading));paint();if(show){message.textContent="Progresso salvo neste dispositivo.";setTimeout(()=>message.textContent="",2500)}}
function paint(){const r=reading[id],page=Math.max(0,Math.min(total,Number(r.page)||0)),pct=Math.round(page/total*100);input.value=page;fill.style.width=`${pct}%`;label.textContent=`${pct}% concluído`;document.querySelectorAll("[data-reading-status]").forEach(b=>b.classList.toggle("active",b.dataset.readingStatus===r.status));mainButton.textContent=r.status==="lendo"?"Continuar lendo":r.status==="desisti"?"Retomar leitura":"Começar a ler"}
function setStatus(status){reading[id]??={page:0};reading[id].status=status;if(status==="lendo"&&reading[id].page===0)reading[id].page=1;save()}
input.addEventListener("input",()=>{const p=Math.max(0,Math.min(total,Number(input.value)||0));reading[id].page=p;if(p>0)reading[id].status="lendo";paint()});document.querySelector("#save-progress").addEventListener("click",()=>save());document.querySelectorAll("[data-reading-status]").forEach(b=>b.addEventListener("click",()=>setStatus(b.dataset.readingStatus)));mainButton.addEventListener("click",()=>setStatus("lendo"));
document.querySelector("#logout").addEventListener("click",()=>signOut(auth));onAuthStateChanged(auth,u=>{if(!u){location.replace("../index.html");return}user=u;document.querySelector("#reader-name").textContent=(u.displayName||"Leitor").split(" ")[0];document.querySelector("#reader-photo").src=u.photoURL||avatar(u.displayName);load();document.body.classList.remove("auth-pending")});